name: CI

on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          - x86
        node:
          - 10
          - 12
          - 14
          - 16
          - 18
        os:
          - macOS-latest
          - ubuntu-22.04
          - ubuntu-24.04
          - windows-latest
        exclude:
          - arch: x86
            os: macOS-latest
          - arch: x86
            os: ubuntu-22.04
          - arch: x86
            os: ubuntu-24.04
          - node: 10
            os: macOS-latest
          - node: 12
            os: macOS-latest
          - node: 14
            os: macOS-latest
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2022-05-01T19%3A09%3A35.949000Z@time-machines-npm.sealsecurity.io/
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
      - run: npm install
      - run: npm test
      - name: Pack the release tarball
        if: matrix.os == 'ubuntu-24.04' && matrix.node == 18 && matrix.arch == 'x64'
        run: npm pack
      - name: Upload the release tarball
        if: matrix.os == 'ubuntu-24.04' && matrix.node == 18 && matrix.arch == 'x64'
        uses: actions/upload-artifact@v4
        with:
          name: npm-tarball
          path: '*.tgz'
          if-no-files-found: error
      - run: echo ::set-output name=job_id::$(node -e "console.log(crypto.randomBytes(16).toString('hex'))")
        id: get_job_id
        shell: bash
    timeout-minutes: 40
